plugins {
    id 'java'
}

group 'org.mentalizr'
version '0.0.9-SNAPSHOT'

repositories {
    maven { url "https://raw.githubusercontent.com/arthurpicht/mvn-repo/main/releases"}
    mavenCentral()
}

dependencies {
    implementation libs.ap.utils.core

    testImplementation libs.ap.utils.io

    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.engine
}

test {
    useJUnitPlatform()
}

task cleanLibsDir(type: Delete) {
    def dirName = fileTree(dir: 'bin/libs', include: '*.jar')
    delete dirName
}

task extractDependencies(type: Copy) {
    into "bin/libs"
    from configurations.runtimeClasspath
}

task prepareTooling() {

}

extractDependencies.dependsOn jar
extractDependencies.dependsOn cleanLibsDir
prepareTooling.dependsOn extractDependencies
